# 1. Numpy Random notebook: 
#### A jupyter notebook explaining the con-cepts behind and the use of the numpy random package, including plots of the various distributions.



In [1]:
import numpy as np

In [2]:
np.random.rand()

0.8414237596973354

In [3]:
np.random.rand(5)

array([2.26120142e-01, 7.18916310e-03, 4.38285672e-01, 2.05232017e-04,
       2.77958112e-01])

In [4]:
np.random.rand(2, 2, 2)

array([[[0.65340779, 0.45069331],
        [0.91127549, 0.6997259 ]],

       [[0.23082841, 0.45238816],
        [0.42366578, 0.72355006]]])

In [5]:
np.random.rand(2,2,2,2)

array([[[[0.44600316, 0.76332262],
         [0.61895578, 0.53499085]],

        [[0.05988805, 0.54473697],
         [0.68909296, 0.58315157]]],


       [[[0.40742814, 0.05597118],
         [0.92121124, 0.79309098]],

        [[0.91599688, 0.93534552],
         [0.98045968, 0.83916077]]]])